//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4dotsFreePDFCompress {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResTranslate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResTranslate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_4dotsFreePDFCompress.ResTranslate", typeof(ResTranslate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version has been released. Press the OK button to download the new version.
        /// </summary>
        internal static string A_new_version_has_been_released__Press_the_OK_button_to_download_the_new_version {
            get {
                return ResourceManager.GetString("A new version has been released. Press the OK button to download the new version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version has been released. Would you like to download it now ?.
        /// </summary>
        internal static string A_new_version_has_been_released__Would_you_like_to_download_it_now__ {
            get {
                return ResourceManager.GetString("A new version has been released. Would you like to download it now ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Subdirectories ?.
        /// </summary>
        internal static string Add_Subdirectories__ {
            get {
                return ResourceManager.GetString("Add Subdirectories ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured !.
        /// </summary>
        internal static string An_error_occured__ {
            get {
                return ResourceManager.GetString("An error occured !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured !\n.
        /// </summary>
        internal static string An_error_occured___n {
            get {
                return ResourceManager.GetString("An error occured !\\n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while protecting PDF File.
        /// </summary>
        internal static string An_error_occured_while_protecting_PDF_File {
            get {
                return ResourceManager.GetString("An error occured while protecting PDF File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PDF Properties.
        /// </summary>
        internal static string Change_PDF_Properties {
            get {
                return ResourceManager.GetString("Change PDF Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress / Decompress PDF.
        /// </summary>
        internal static string Compress___Decompress_PDF {
            get {
                return ResourceManager.GetString("Compress / Decompress PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date and Time.
        /// </summary>
        internal static string Creation_Date_and_Time {
            get {
                return ResourceManager.GetString("Creation Date and Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Custom Date.
        /// </summary>
        internal static string Current_Custom_Date {
            get {
                return ResourceManager.GetString("Current Custom Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Date.
        /// </summary>
        internal static string Current_Date {
            get {
                return ResourceManager.GetString("Current Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Date and Time.
        /// </summary>
        internal static string Current_Date_and_Time {
            get {
                return ResourceManager.GetString("Current Date and Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Day (DD).
        /// </summary>
        internal static string Current_Day__DD_ {
            get {
                return ResourceManager.GetString("Current Day (DD)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Hour (HH).
        /// </summary>
        internal static string Current_Hour__HH_ {
            get {
                return ResourceManager.GetString("Current Hour (HH)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Minute (MI).
        /// </summary>
        internal static string Current_Minute__MI_ {
            get {
                return ResourceManager.GetString("Current Minute (MI)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Month (MM).
        /// </summary>
        internal static string Current_Month__MM_ {
            get {
                return ResourceManager.GetString("Current Month (MM)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Second (SS).
        /// </summary>
        internal static string Current_Second__SS_ {
            get {
                return ResourceManager.GetString("Current Second (SS)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Time.
        /// </summary>
        internal static string Current_Time {
            get {
                return ResourceManager.GetString("Current Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Year (YYYY).
        /// </summary>
        internal static string Current_Year__YYYY_ {
            get {
                return ResourceManager.GetString("Current Year (YYYY)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Name.
        /// </summary>
        internal static string Directory_Name {
            get {
                return ResourceManager.GetString("Directory Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Path.
        /// </summary>
        internal static string Directory_Path {
            get {
                return ResourceManager.GetString("Directory Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download new version ?.
        /// </summary>
        internal static string Download_new_version__ {
            get {
                return ResourceManager.GetString("Download new version ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt PDF.
        /// </summary>
        internal static string Encrypt_PDF {
            get {
                return ResourceManager.GetString("Encrypt PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not Create Directory for File.
        /// </summary>
        internal static string Error__Could_not_Create_Directory_for_File {
            get {
                return ResourceManager.GetString("Error. Could not Create Directory for File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not send Questionnaire !.
        /// </summary>
        internal static string Error__Could_not_send_Questionnaire__ {
            get {
                return ResourceManager.GetString("Error. Could not send Questionnaire !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Wrong User Password for File.
        /// </summary>
        internal static string Error__Wrong_User_Password_for_File {
            get {
                return ResourceManager.GetString("Error. Wrong User Password for File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Could not change Language !.
        /// </summary>
        internal static string Error_Could_not_change_Language__ {
            get {
                return ResourceManager.GetString("Error Could not change Language !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not parse Arguments !.
        /// </summary>
        internal static string Error_could_not_parse_Arguments__ {
            get {
                return ResourceManager.GetString("Error could not parse Arguments !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename Without Extension.
        /// </summary>
        internal static string Filename_Without_Extension {
            get {
                return ResourceManager.GetString("Filename Without Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full File Path.
        /// </summary>
        internal static string Full_File_Path {
            get {
                return ResourceManager.GetString("Full File Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I did find a free application to compress PDF files !.
        /// </summary>
        internal static string I_did_find_a_free_application_to_compress_PDF_files__ {
            get {
                return ResourceManager.GetString("I did find a free application to compress PDF files !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is From Windows Explorer.
        /// </summary>
        internal static string Is_From_Windows_Explorer {
            get {
                return ResourceManager.GetString("Is From Windows Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Access Date and Time.
        /// </summary>
        internal static string Last_Access_Date_and_Time {
            get {
                return ResourceManager.GetString("Last Access Date and Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Write Date and Time.
        /// </summary>
        internal static string Last_Write_Date_and_Time {
            get {
                return ResourceManager.GetString("Last Write Date and Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Cancelled !.
        /// </summary>
        internal static string Operation_Cancelled__ {
            get {
                return ResourceManager.GetString("Operation Cancelled !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully !.
        /// </summary>
        internal static string Operation_completed_successfully__ {
            get {
                return ResourceManager.GetString("Operation completed successfully !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed with Errors !.
        /// </summary>
        internal static string Operation_completed_with_Errors__ {
            get {
                return ResourceManager.GetString("Operation completed with Errors !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite PDF Document.
        /// </summary>
        internal static string Overwrite_PDF_Document {
            get {
                return ResourceManager.GetString("Overwrite PDF Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a PDF File first !.
        /// </summary>
        internal static string Please_add_a_PDF_File_first__ {
            get {
                return ResourceManager.GetString("Please add a PDF File first !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add only PDF Files !.
        /// </summary>
        internal static string Please_add_only_PDF_Files__ {
            get {
                return ResourceManager.GetString("Please add only PDF Files !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add PDF Files first !.
        /// </summary>
        internal static string Please_add_PDF_Files_first__ {
            get {
                return ResourceManager.GetString("Please add PDF Files first !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Subfolder Name !.
        /// </summary>
        internal static string Please_enter_a_Subfolder_Name__ {
            get {
                return ResourceManager.GetString("Please enter a Subfolder Name !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Subfolder Name !.
        /// </summary>
        internal static string Please_enter_a_valid_Subfolder_Name__ {
            get {
                return ResourceManager.GetString("Please enter a valid Subfolder Name !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the correct User Password !.
        /// </summary>
        internal static string Please_enter_the_correct_User_Password__ {
            get {
                return ResourceManager.GetString("Please enter the correct User Password !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the Questionnaire !.
        /// </summary>
        internal static string Please_fill_out_the_Questionnaire__ {
            get {
                return ResourceManager.GetString("Please fill out the Questionnaire !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a Custom Metadata Property Name !.
        /// </summary>
        internal static string Please_insert_a_Custom_Metadata_Property_Name__ {
            get {
                return ResourceManager.GetString("Please insert a Custom Metadata Property Name !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a valid Password !.
        /// </summary>
        internal static string Please_insert_a_valid_Password__ {
            get {
                return ResourceManager.GetString("Please insert a valid Password !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an existing output folder !.
        /// </summary>
        internal static string Please_specify_an_existing_output_folder__ {
            get {
                return ResourceManager.GetString("Please specify an existing output folder !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify another option as the Output Folder !.
        /// </summary>
        internal static string Please_specify_another_option_as_the_Output_Folder__ {
            get {
                return ResourceManager.GetString("Please specify another option as the Output Folder !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify PDF Files to Compress or Decompress !.
        /// </summary>
        internal static string Please_specify_PDF_Files_to_Compress_or_Decompress__ {
            get {
                return ResourceManager.GetString("Please specify PDF Files to Compress or Decompress !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Folder of PDF Document.
        /// </summary>
        internal static string Same_Folder_of_PDF_Document {
            get {
                return ResourceManager.GetString("Same Folder of PDF Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfolder.
        /// </summary>
        internal static string Subfolder {
            get {
                return ResourceManager.GetString("Subfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfolder of PDF Document.
        /// </summary>
        internal static string Subfolder_of_PDF_Document {
            get {
                return ResourceManager.GetString("Subfolder of PDF Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the latest version !.
        /// </summary>
        internal static string This_is_the_latest_version__ {
            get {
                return ResourceManager.GetString("This is the latest version !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified Error.
        /// </summary>
        internal static string Unspecified_Error {
            get {
                return ResourceManager.GetString("Unspecified Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to add also Subdirectories ?.
        /// </summary>
        internal static string Would_you_like_to_add_also_Subdirectories__ {
            get {
                return ResourceManager.GetString("Would you like to add also Subdirectories ?", resourceCulture);
            }
        }
    }
}
